[phases.setup]
nixLibs = ["...", "zlib", "gcc-unwrapped", "stdenv.cc.cc.lib"]
aptPkgs = ["...", "libstdc++6", "zlib1g", "libgomp1", "libgfortran5"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "chmod +x start.sh",
]

[start]
cmd = "sh start.sh"
